name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install Go tools
      run: |
        go install github.com/go-python/gopy@latest
        go install golang.org/x/tools/cmd/goimports@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        
    - name: Debug environment
      run: |
        which gopy
        which goimports
        echo $PATH
        ls -la src/

    - name: Install build deps
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel PyBindGen

    - name: Fix build.py for GitHub Actions
      run: |
        cat > patch.py << 'EOF'
        #!/usr/bin/env python3
        
        with open('build.py', 'r') as f:
          content = f.read()
          
        # Patch the gopy command to skip using "go build -v ."
        patched = content.replace('subprocess.call(cmd, env=env, cwd=temp_dir)', 
                                 'subprocess.call(cmd + ["-no-make"], env=env, cwd=temp_dir)')
        
                with open('build.py', 'w') as f:
          f.write(patched)
        EOF
        
        python patch.py

    - name: Build library
      run: python src/build.py build

    - name: Build wheel
      run: python src/build.py bdist_wheel

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ matrix.os }}-py${{ matrix.python-version }}
        path: dist/*.whl

    - name: Upload compiled library
      uses: actions/upload-artifact@v4
      with:
        name: lib-${{ matrix.os }}-py${{ matrix.python-version }}
        path: ohbother/**/*