name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest] #[ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install Go tools
      run: |
        go install github.com/go-python/gopy@latest
        go install golang.org/x/tools/cmd/goimports@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        
    - name: Debug environment
      run: |
        which gopy
        which goimports
        echo $PATH
        ls -la src/

    - name: Install build deps
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel PyBindGen

    # Linux: Add LD_LIBRARY_PATH
    - name: Set LD_LIBRARY_PATH for Linux
      if: runner.os == 'Linux'
      run: echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:." >> $GITHUB_ENV

    # Build library - Platform specific commands
    - name: Build library (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        cd src
        python build.py build
      env:
        LD_LIBRARY_PATH: ${{ env.LD_LIBRARY_PATH }}:. # Add current dir to path
        
    - name: Build library (Windows)
      if: runner.os == 'Windows'
      run: |
        cd src
        py build.py build
        
    # Build wheel - Platform specific commands
    - name: Build wheel (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        cd src
        python build.py bdist_wheel
      env:
        LD_LIBRARY_PATH: ${{ env.LD_LIBRARY_PATH }}:. # Add current dir to path
        
    - name: Build wheel (Windows)
      if: runner.os == 'Windows'
      run: |
        cd src
        py build.py bdist_wheel

    # Upload artifacts - same for all platforms
    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ matrix.os }}-py${{ matrix.python-version }}
        path: src/dist/*.whl

    - name: Upload compiled library
      uses: actions/upload-artifact@v4
      with:
        name: lib-${{ matrix.os }}-py${{ matrix.python-version }}
        path: src/ohbother/**/*