name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        python-version: ['3.11'] #, '3.12', '3.13'] # Will add 3.10 once fixed

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Run go mod tidy
      working-directory: ./src
      run: go mod tidy

    - name: Install goimports
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        # Ensure GOPATH/bin is in PATH for subsequent steps
        echo "${{ runner.tool_cache }}/go/1.24.0/x64/bin" >> $GITHUB_PATH

    - name: Install gopy
      run: go install github.com/go-python/gopy@latest

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel PyBindGen

    - name: Create ohbother directory
      run: mkdir -p ohbother

    - name: Build library
      run: python build.py build

    - name: Build wheel package
      run: python build.py bdist_wheel

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
        path: dist/*.whl

    - name: Upload compiled library
      uses: actions/upload-artifact@v4
      with:
        name: library-${{ matrix.os }}-py${{ matrix.python-version }}
        path: ohbother/**/*