name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        python-version: ['3.11'] #, '3.12', '3.13'] # Will add 3.10 once fixed

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Run go mod tidy
      run: cd src && go mod tidy

    - name: Install gopy
      run: go install github.com/go-python/gopy@latest

    - name: Install build deps
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel PyBindGen

    - name: Build library
      run: python build.py build

    - name: Build wheel
      run: python build.py bdist_wheel

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ matrix.os }}-py${{ matrix.python-version }}
        path: dist/*.whl

    - name: Upload compiled library
      uses: actions/upload-artifact@v4
      with:
        name: lib-${{ matrix.os }}-py${{ matrix.python-version }}
        path: ohbother/**/*